//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the VIP Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import Foundation

protocol ___VARIABLE_sceneName___InteractorProtocol {
  
  func doRequest()
}


final class ___VARIABLE_sceneName___Interactor {
    
  private var presenter: ___VARIABLE_sceneName___PresenterProtocol
  private var worker: ___VARIABLE_sceneName___WorkerProtocol

  init(worker: ___VARIABLE_sceneName___WorkerProtocol, presenter: ___VARIABLE_sceneName___PresenterProtocol) {
    self.worker = worker
    self.presenter = presenter
  }
}


extension ___VARIABLE_sceneName___Interactor: ___VARIABLE_sceneName___InteractorProtocol {
    func doRequest(){
       self.worker.executeRequest(completion: { [weak self] data in
            self?.presenter.didSucess()
        })
    }
}
